function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "SmartTrackerFilter"};
	this.sidHashMap["SmartTrackerFilter"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "SmartTrackerFilter:135"};
	this.sidHashMap["SmartTrackerFilter:135"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "SmartTrackerFilter:135:2"};
	this.sidHashMap["SmartTrackerFilter:135:2"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<Root>/rawAccelIn"] = {sid: "SmartTrackerFilter:103"};
	this.sidHashMap["SmartTrackerFilter:103"] = {rtwname: "<Root>/rawAccelIn"};
	this.rtwnameHashMap["<Root>/Decimator100"] = {sid: "SmartTrackerFilter:149"};
	this.sidHashMap["SmartTrackerFilter:149"] = {rtwname: "<Root>/Decimator100"};
	this.rtwnameHashMap["<Root>/Decimator25"] = {sid: "SmartTrackerFilter:151"};
	this.sidHashMap["SmartTrackerFilter:151"] = {rtwname: "<Root>/Decimator25"};
	this.rtwnameHashMap["<Root>/Decimator50"] = {sid: "SmartTrackerFilter:150"};
	this.sidHashMap["SmartTrackerFilter:150"] = {rtwname: "<Root>/Decimator50"};
	this.rtwnameHashMap["<Root>/GravFilter"] = {sid: "SmartTrackerFilter:135"};
	this.sidHashMap["SmartTrackerFilter:135"] = {rtwname: "<Root>/GravFilter"};
	this.rtwnameHashMap["<Root>/SpeedIntegrator"] = {sid: "SmartTrackerFilter:142"};
	this.sidHashMap["SmartTrackerFilter:142"] = {rtwname: "<Root>/SpeedIntegrator"};
	this.rtwnameHashMap["<Root>/gToMperS"] = {sid: "SmartTrackerFilter:152"};
	this.sidHashMap["SmartTrackerFilter:152"] = {rtwname: "<Root>/gToMperS"};
	this.rtwnameHashMap["<Root>/gravExtractor"] = {sid: "SmartTrackerFilter:146"};
	this.sidHashMap["SmartTrackerFilter:146"] = {rtwname: "<Root>/gravExtractor"};
	this.rtwnameHashMap["<Root>/speedOut"] = {sid: "SmartTrackerFilter:121"};
	this.sidHashMap["SmartTrackerFilter:121"] = {rtwname: "<Root>/speedOut"};
	this.rtwnameHashMap["<Root>/gravOut"] = {sid: "SmartTrackerFilter:147"};
	this.sidHashMap["SmartTrackerFilter:147"] = {rtwname: "<Root>/gravOut"};
	this.rtwnameHashMap["<S1>/In1"] = {sid: "SmartTrackerFilter:135:1"};
	this.sidHashMap["SmartTrackerFilter:135:1"] = {rtwname: "<S1>/In1"};
	this.rtwnameHashMap["<S1>/Check Signal Attributes"] = {sid: "SmartTrackerFilter:135:2"};
	this.sidHashMap["SmartTrackerFilter:135:2"] = {rtwname: "<S1>/Check Signal Attributes"};
	this.rtwnameHashMap["<S1>/Digital Filter"] = {sid: "SmartTrackerFilter:135:28"};
	this.sidHashMap["SmartTrackerFilter:135:28"] = {rtwname: "<S1>/Digital Filter"};
	this.rtwnameHashMap["<S1>/Out1"] = {sid: "SmartTrackerFilter:135:4"};
	this.sidHashMap["SmartTrackerFilter:135:4"] = {rtwname: "<S1>/Out1"};
	this.rtwnameHashMap["<S2>/In1"] = {sid: "SmartTrackerFilter:135:2:1"};
	this.sidHashMap["SmartTrackerFilter:135:2:1"] = {rtwname: "<S2>/In1"};
	this.rtwnameHashMap["<S2>/Check Signal Attributes"] = {sid: "SmartTrackerFilter:135:2:2"};
	this.sidHashMap["SmartTrackerFilter:135:2:2"] = {rtwname: "<S2>/Check Signal Attributes"};
	this.rtwnameHashMap["<S2>/Out1"] = {sid: "SmartTrackerFilter:135:2:3"};
	this.sidHashMap["SmartTrackerFilter:135:2:3"] = {rtwname: "<S2>/Out1"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
